language: cpp

compiler:
  - gcc
  
before_install:
  - if [[ $CXX == g++ ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"; fi
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key|sudo apt-key add - && sudo apt-get update && sudo apt-get install clang-3.6 libclang-common-3.6-dev libclang-3.6-dev libclang1-3.6 libclang1-3.6-dbg libllvm-3.6-ocaml-dev libllvm3.6 libllvm3.6-dbg llvm-3.6 llvm-3.6-dev llvm-3.6-examples llvm-3.6-runtime clang-modernize-3.6 clang-format-3.6 
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j
