language: cpp

compiler:
  - gcc
  
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9";
  - sudo add-apt-repository -y ppa:h-rayflood/llvm;
  - sudo add-apt-repository --yes ppa:ubuntu-toolchain-r/test;
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise main' >> /etc/apt/sources.list";
  - sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.6 main' >> /etc/apt/sources.list" && sudo apt-get update;
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -;
  - sudo apt-get update && sudo apt-get install -y clang-3.6 libclang1-3.6 llvm-3.6 && export CXX="clang++-3.6" CC="clang-3.6";
  

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j
