language: cpp

compiler:
  - gcc
  
before_install:
- if [[ $CXX == g++ ]]; then sudo apt-get update; sudo apt-get search "gcc"; fi

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j
