language: cpp

compiler:
  - gcc
  
before_install:
  - if [[ $CXX == g++ ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install -y g++-4.9 && export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo add-apt-repository -y http://llvm.org/apt/precise/ && sudo apt-get update && sudo apt-get install libclang-3.5 && sudo apt-get install llvm-3.5
before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j
